### ISSUE TITLE
refine idea and outline project in the design docs

### ISSUE THREAD

**Issue by RobertLikesCoding** [RobertLikesCoding/QuizCraft#2]
- [x]  review AI options
- [ ]  go through design docs
- [x]  refine vision of the app
- [x]  complete tech stack

**Comment by lyzboy** [comment]
Do we feel that this task has been resolved? Should we review the initial design doc in order to mark this task complete and move on to specific design documentation?

**Comment by RobertLikesCoding** [comment]
Yeah, lets close it. We can make another task for the Docs later when we start working on them and since that is going to be a long term task of its own.
